USE [master]
GO

/****** Object:  Database [BdForSalesAnalysis]    Script Date: 23.08.2025 19:05:33 ******/
DROP DATABASE [BdForSalesAnalysis]
GO

/****** Object:  Database [BdForSalesAnalysis]    Script Date: 23.08.2025 19:05:33 ******/
CREATE DATABASE [BdForSalesAnalysis]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'BdForSalesAnalysis', FILENAME = N'C:\Users\Wolf\source\BdForSalesAnalysis.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'BdForSalesAnalysis_log', FILENAME = N'C:\Users\Wolf\source\BdForSalesAnalysis_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT, LEDGER = OFF
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [BdForSalesAnalysis].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [BdForSalesAnalysis] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [BdForSalesAnalysis] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [BdForSalesAnalysis] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [BdForSalesAnalysis] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [BdForSalesAnalysis] SET ARITHABORT OFF 
GO

ALTER DATABASE [BdForSalesAnalysis] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [BdForSalesAnalysis] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [BdForSalesAnalysis] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [BdForSalesAnalysis] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [BdForSalesAnalysis] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [BdForSalesAnalysis] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [BdForSalesAnalysis] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [BdForSalesAnalysis] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [BdForSalesAnalysis] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [BdForSalesAnalysis] SET  DISABLE_BROKER 
GO

ALTER DATABASE [BdForSalesAnalysis] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [BdForSalesAnalysis] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [BdForSalesAnalysis] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [BdForSalesAnalysis] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [BdForSalesAnalysis] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [BdForSalesAnalysis] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [BdForSalesAnalysis] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [BdForSalesAnalysis] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [BdForSalesAnalysis] SET  MULTI_USER 
GO

ALTER DATABASE [BdForSalesAnalysis] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [BdForSalesAnalysis] SET DB_CHAINING OFF 
GO

ALTER DATABASE [BdForSalesAnalysis] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [BdForSalesAnalysis] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [BdForSalesAnalysis] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [BdForSalesAnalysis] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [BdForSalesAnalysis] SET QUERY_STORE = ON
GO

ALTER DATABASE [BdForSalesAnalysis] SET QUERY_STORE (OPERATION_MODE = READ_WRITE, CLEANUP_POLICY = (STALE_QUERY_THRESHOLD_DAYS = 30), DATA_FLUSH_INTERVAL_SECONDS = 900, INTERVAL_LENGTH_MINUTES = 60, MAX_STORAGE_SIZE_MB = 1000, QUERY_CAPTURE_MODE = AUTO, SIZE_BASED_CLEANUP_MODE = AUTO, MAX_PLANS_PER_QUERY = 200, WAIT_STATS_CAPTURE_MODE = ON)
GO

ALTER DATABASE [BdForSalesAnalysis] SET  READ_WRITE 
GO


